# Base build configuration
# Creates a minimal VM template with cloud-init

base:
  build_vars:
    proxmox_template_name: "{{ distro_slug }}-base"
    proxmox_template_description: "Base template with cloud-init"
  distros:
    debian/bookworm: {}
  builders:
    proxmox-iso: {}
  provisioners:
    - debian-cloud
