# PIM Default Target Configuration
# Base settings inherited by all targets

default:
  # VM resources
  memory: 2048
  cores: 2
  disk_size: 20G

  # SSH settings for packer
  ssh_username: ansible
  ssh_password: changeme
  ssh_timeout: 30m

  # Boot wait time
  boot_wait: 5s

  # Shutdown command
  shutdown_command: "echo 'changeme' | sudo -S shutdown -P now"
